spring:
  application:
    name: notification-service
    kafka:
      bootstrap-servers: localhost:9092
      consumer:
        group-id: email-group
        auto-offset-reset: earliest
        key-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer

  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  kafka:
    topic: notification-topic
  email:
    from: your-mail@gmail.com
    defaultSubject: Notification from Kafka
    defaultBody: This is a notification from Kafka.
    retry:
      max-attempts: 3
      backoff:
        delay: 2000
        multiplier: 2.0

logging:
  level:
    root: INFO
    com.manasa.notificationservice: DEBUG
  file:
    name: logs/notification-service.log